### ISSUE TITLE
Identify components

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-storybook#4]
Create a list of the existing components on MDN Web Docs.

**Comment by schalkneethling** [comment]
# Components

If ticked, the component has also been added to Storybook

- [ ] nav-access
- [ ] Loading bar
- [x] Logo
- [x] Main nav
- [ ] Search widget
- [ ] Sign in
- [ ] Signed in widget
- [ ] Title bar
- [ ] Breadcrumbs
- [ ] Lang selector
- [ ] TOC
- [ ] Article content
- [ ] Sidebar
- [ ] Last modified
- [ ] Newsletter
- [ ] Footer

**Comment by Gregoor** [comment]
Do we also want to list KS components? Like the BCD table? I'd guess so because sidebar is KS, right?

**Comment by schalkneethling** [comment]
> Do we also want to list KS components? Like the BCD table? I'd guess so because sidebar is KS, right?

Most definitely, good call @Gregoor
